'use strict';

export const SET_SECTIONS = 'SET_SECTIONS';
export const SET_CURRENT_SECTION = 'SET_CURRENT_SECTION';
export const SET_MODIFIABLE_SECTION = 'SET_MODIFIABLE_SECTION';

export const SET_CURRENT_SUBSECTION = 'SET_CURRENT_SUBSECTION';

export const SET_CURRENT_CHANNEL = 'SET_CURRENT_CHANNEL';
export const SET_CURRENT_USER_CHANNEL = 'SET_CURRENT_USER_CHANNEL';

export const SET_USER_INFO = 'SET_USER_INFO';


//remote actions
export const UPDATE_SECTIONS = 'UPDATE_SECTIONS';

export const UPDATE_SUBSECTIONS = 'UPDATE_SUBSECTIONS';

export const UPDATE_CHANNELS = 'UPDATE_CHANNELS';

export const UPDATE_MESSAGES = 'UPDATE_MESSAGES';

export const UPDATE_USER_INFO = 'UPDATE_USER_INFO';



