'use strict';

export const SET_SECTIONS = 'SET_SECTIONS';
export const SET_CURRENT_SECTION = 'SET_CURRENT_SECTION';
export const SET_CURRENT_INFO_SECTION = 'SET_CURRENT_INFO_SECTION';
export const SET_MODIFIABLE_SECTION = 'SET_MODIFIABLE_SECTION';

export const SET_CURRENT_SUBSECTION = 'SET_CURRENT_SUBSECTION';
export const SET_CURRENT_INFO_SUBSECTION = 'SET_CURRENT_INFO_SUBSECTION';
export const SET_MODIFIABLE_SUBSECTION = 'SET_MODIFIABLE_SUBSECTION';

export const SET_CURRENT_CHANNEL = 'SET_CURRENT_CHANNEL';
export const SET_CURRENT_INFO_CHANNEL = 'SET_CURRENT_INFO_CHANNEL';
export const SET_MODIFIABLE_CHANNEL = 'SET_MODIFIABLE_CHANNEL';

export const SET_CURRENT_INFO_MESSAGE = 'SET_CURRENT_INFO_MESSAGE';
export const SET_MODIFIABLE_MESSAGE = 'SET_MODIFIABLE_MESSAGE';

export const SET_ALERT_DATA = 'SET_ALERT_DATA';

export const SET_CURRENT_USER_CHANNEL = 'SET_CURRENT_USER_CHANNEL';

export const SET_CURRENT_USER_INFO = 'SET_CURRENT_USER_INFO';
export const SET_MODIFIABLE_USER_INFO = 'SET_MODIFIABLE_USER_INFO';


//remote actions
export const JOIN_ROOM = 'JOIN_ROOM';
export const LEAVE_ROOM = 'LEAVE_ROOM';

export const UPDATE_SECTIONS = 'UPDATE_SECTIONS';

export const UPDATE_SECTION_BY_ID = 'UPDATE_SECTION_BY_ID';
export const DELETE_SECTION_BY_ID = 'DELETE_SECTION_BY_ID';

export const UPDATE_SUBSECTION_BY_ID = 'UPDATE_SUBSECTION_BY_ID';
export const DELETE_SUBSECTION_BY_ID = 'DELETE_SUBSECTION_BY_ID';

export const UPDATE_CHANNEL_BY_ID = 'UPDATE_CHANNEL_BY_ID';
export const DELETE_CHANNEL_BY_ID = 'DELETE_CHANNEL_BY_ID';

export const UPDATE_MESSAGE_BY_ID = 'UPDATE_MESSAGE_BY_ID';
export const DELETE_MESSAGE_BY_ID = 'DELETE_MESSAGE_BY_ID';

export const UPDATE_USER_INFO = 'UPDATE_USER_INFO';




